import { Injectable } from '@angular/core';
import { ConstructionService } from './construction.service';
import { ToolManagerService } from './tool-manager.service';
import { ViewStateService } from '../view/services/view-state.service';
import { PassiveTool, isPassiveTool } from './interfaces/passiveTool-interface';
import { LlmServiceService } from '../view/services/llm-service.service';


@Injectable({
  providedIn: 'root',
})
export class ValidationService {
  private dependencyMessages: Record<string, (step: any) => string> = {
    segment: () => 'Please draw the required segment first.',
    protractor: (step) => {
      const dependentStep = this.getGeoElementByStepId(step.depends[0]);
      return `Please place the protractor on the base segment ${dependentStep.start.label}${dependentStep.end.label}.`;
    },
    point: () => 'Please plot the required point first.',
  };

  configForHint: any = {};

  private config: any;
  private steps: any;
  private completedStepMap = new Map<number, number>(); // stepId → geoIndex
  private deferredSteps = new Map<
    number,
    { depends: number[]; geoIndex: number }
  >();
  currentStepId: number | null = null;

  constructor(
    private constructionService: ConstructionService,
    private toolManager: ToolManagerService,
    private viewState: ViewStateService,
    private llm: LlmServiceService
  ) {}

  loadConfig(config: any): void {
    this.config = config;
    this.steps = config.steps;
    this.configForHint['labelSensitive'] = this.config.labelSensitive;
  }

  reset(): void {
    this.completedStepMap.clear();
  }

  getPendingSteps(tool?: string): any[] {
    return this.config.steps.filter(
      (step: any) => !this.completedStepMap.has(step.id) && step.tool === tool
    );
  }

  isStepCompleted(stepId: number): boolean {
    return this.completedStepMap.has(stepId);
  }

  markStepAsCompleted(stepId: number, geoIndex: number): void {
    this.completedStepMap.set(stepId, geoIndex);
  }

  getGeoElementByStepId(stepId: number): any | null {
    const geoIndex = this.completedStepMap.get(stepId);
    console.log(this.constructionService.getGeoElements(), geoIndex);
    const obj =
      geoIndex !== undefined
        ? this.constructionService.getGeoElements()[geoIndex]
        : null;
    return obj;
  }

  isComplete(): boolean {
    return this.completedStepMap.size === this.config.steps.length;
  }

  async identifyStep(userObject: any, toolSelected: string): Promise<any> {
    try {
      console.log(this.completedStepMap);
      const stepIdentification = await this.llm.identifyStep({
        userObject,
        pendingSteps:this.getPendingSteps(toolSelected),
        labelSensitive: this.config.labelSensitive
      });
      console.log('Step identified by assistant:', stepIdentification);

      debugger
      return stepIdentification;
      // Optionally emit or handle the result
    } catch (err) {
      console.error('Error during step identification:', err);
      return '';
    }
  }
  async generateHints(config: any) {
    try {
      console.log(this.completedStepMap);
      if (this.isComplete())
        config.reason = 'You have succesfully completed the question';
      config.labelSensitive = this.config.labelSensitive;
      const result = await this.llm.generateHints({
        config,
        completedStepMap: this.completedStepMap
      });
      console.log('hint generated by assistant:', result);

      this.viewState.emitmessage(result.message);

      // Optionally emit or handle the result
    } catch (err) {
      console.error('Error during step identification:', err);
    }
  }
  async startValidation() {
    this.configForHint ={};
    const elements = this.constructionService.getGeoElements();
    if (!elements.length) return;

    const lastIndex = elements?.length - 1;
    const lastElement = elements[lastIndex];
    const tool = lastElement.tool;
    const toolService =
      this.toolManager.toolMap[tool] || this.getPassiveTool(tool);
    const pendingSteps = this.getPendingSteps();
    if (!toolService || !lastElement) return;

    // this.viewState.emitmessage(null);

    console.log(lastElement);
    const stepToMatch = await this.identifyStep(lastElement, tool);

    console.log(stepToMatch);
    const stepId = stepToMatch.stepId;

    this.configForHint['errorType'] = stepToMatch.errorType;
    if (!stepId) {
      this.configForHint['userStep'] = null;
      return;
      // const expectedStep = this.config.steps[stepToMatch.expectedStepId - 1];
      // this.configForHint['expectedStep'] = expectedStep;
    } else {
      const step = this.config.steps[stepId - 1];
      console.log('step from question:', step);
      this.configForHint['userStep'] = lastElement;
      this.configForHint['actualStep'] = step;
      const depsMet = this.validateDependency(step);
      if (!depsMet && !this.isStepCompleted(stepId)) {
        const firstUnmet = this.getFirstIncompleteDependency(step);
        const unmetDependencyStep = this.findStepById(firstUnmet);
        this.configForHint['dependentStep'] =
          this.config.steps[unmetDependencyStep];
        this.configForHint['validated'] = depsMet;
        this.configForHint['reason'] =
          this.dependencyMessages[unmetDependencyStep.tool](
            unmetDependencyStep
          ) || null;
      } else {
        debugger
        const result = toolService.validate(
          step,
          lastElement,
          this.config.labelSensitive
        );
        console.log(result);
        if (result?.data?.baseSegement) {
          const element = this.constructionService.getGeoElements()[lastIndex];
          element.baseSegment = result.data?.baseSegement;
          this.constructionService.updateGeoElement(lastIndex, element);
        }
        if (result.matched){ this.markStepAsCompleted(stepId, lastIndex)
          if(result.reason) this.viewState.emitmessage(
            this.isComplete()? "Great job! You’ve completed this question successfully!" : result.reason)
          return ;
        };
        if (result.data) this.configForHint['userStep']['data'] = {...result.data};
        this.configForHint['validated'] = result.matched;
        this.configForHint['errorType'].push(result.reason);
      }
    }

    console.log(this.configForHint);
    debugger
    await this.generateHints(this.configForHint);

    // for (const step of pendingSteps) {
    //   if (step.tool !== tool) continue;

    //   const depsMet = this.validateDependency(step);
    //   if (!depsMet) {
    //     const firstUnmet = this.getFirstIncompleteDependency(step);
    //     const unmetDependencyStep = this.findStepById(firstUnmet);
    //     this.viewState.emitmessage(
    //       this.dependencyMessages[unmetDependencyStep.tool](
    //         unmetDependencyStep
    //       ) || null
    //     );
    //     return;
    //   }
    //   const result = toolService.validate(
    //     step,
    //     lastElement,
    //     this.config.labelSensitive
    //   );
    //   this.displayMessage(result, step.id, lastIndex);
    //   if (result.matched) break;
    // }
  }

  displayMessage(result: any, stepId: number, lastIndex: number) {
    let message;
    if (result.matched) {
      this.markStepAsCompleted(stepId, lastIndex);
      const element = this.constructionService.getGeoElements()[lastIndex];
      element.baseSegment = result.outputObject;
      this.constructionService.updateGeoElement(lastIndex, element);
      message = null;
      if (this.isComplete()) {
        message = '✅ Well done! You have successfully solved it.';
      } else {
        message = result?.reason || 'Well done!';
      }
    } else {
      message = result.reason;
    }
    this.viewState.emitmessage(message || null);
  }

  // validateDeferedSteps(currentValidatedStepId: number) {
  //   let result;
  //   for (const [stepId, info] of this.deferredSteps) {
  //     if (!info.depends.includes(currentValidatedStepId)) continue;

  //     const depsNowMet = info.depends.every((id) => this.isStepCompleted(id));
  //     if (!depsNowMet) continue;

  //     const element = this.constructionService.getGeoElements()[info.geoIndex];
  //     const step = this.steps.find((s: any) => s.id === stepId);

  //     const toolService: InteractiveTool | PassiveTool =
  //       this.toolManager.toolMap[step.tool] || this.getPassiveTool(step.tool);

  //     if (!toolService) continue;
  //   }
  // }

  private getPassiveTool(toolName: string): PassiveTool | null {
    const tool = this.toolManager.toolMap[toolName];
    return isPassiveTool(tool) ? tool : null;
  }

  validateDependency(step: any) {
    const depsMet =
      !step.depends ||
      step.depends.every((id: number) => this.isStepCompleted(id));
    return depsMet;
  }

  findStepById(stepId: number): any | null {
    return this.steps.find((step: any) => step.id === stepId) || null;
  }
  // Helper to find the first unmet dependency recursively
  private getFirstIncompleteDependency(step: any): number {
    if (!step.depends || step.depends.length === 0) {
      return step.id;
    }

    for (const depId of step.depends) {
      if (!this.isStepCompleted(depId)) {
        const depStep = this.findStepById(depId);
        return this.getFirstIncompleteDependency(depStep);
      }
    }

    // All dependencies met
    return step.id;
  }
}
